#!/usr/bin/env bash
#  Bash script that transfers a file from our client to a server
# checking input
if [ $# -1t 4 ]

then
	echo "Usage: O-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
else
	# strict host checking
	scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~/
fi
