#!/usr/bin/env bash
#Install nginx web server
sudo apt-get -y update
sudo apt-get -y install nginx

echo "Hello World!" | sudo tee /var/www/html/index.html

#test config
sudo nginx -t
sudo service nginx reload
