#!/usr/bin/env bash

# Upadating Packages before Installations
sudo apt-get update
sudo apt-get install -y nginx

# Creating an index.html page
echo "Hello World!" | sudo tee /var/www/html/index.html

#using sed command to perform redirection

redirect_config="location \/redirect_me {return 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;}"
sudo sed -i "/^}$/i \ \n\t$redirect_config" /etc/nginx/sites-available/default

# Restarting Nginx service
sudo service nginx restart
