#!/usr/bin/env bash
#Install nginx web server
sudo apt-get -y update
sudo apt-get -y install nginx

echo "Hello World!" | sudo tee /var/www/html/index.html
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/ permanent;' /etc/nginx/sites-available/default
echo "Hello World!" | sudo tee /var/www/html/not_found_page_404
sudo sed -i '/server {/a\    error_page 404 /error_404.html;' /etc/nginx/sites-available/default

#test config
sudo nginx -t
sudo service nginx start
