#!/usr/bin/env bash

# Bash script that configures a server to the above requirement
# debugging nginx port 80

sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
