#!/usr/bin/env bash
# Bash script that loops from 1 to 10.

num=0

while [ $num -le 9 ]
do
    if [ $num -eq 3 ]
    then
        echo "bad luck"
    elif [ $num -eq 7 ]
    then
        echo "good luck"
    else
        echo "Best School"
    fi
    ((num++))
done
